uboot-env: Exclude do_compile variable from do_assemble_uboot_env
In order to shut up the error:
ERROR: When reparsing u-boot_2014.10.bb.do_assemble_uboot_env,
       the basehash value changed from ...
       The metadata is not deterministic and this needs to be fixed.
Lets exclude do_compile from method do_assemble_uboot_env hash.

Signed-off-by: Serge Semin <fancer.lancer@gmail.com>